### ISSUE TITLE
Pivot tool

### ISSUE THREAD

**Issue by haaranoos** [xyahh/UE4RuntimeTransformer#1]
Hello

Thank you for your great tool. I really appreciate it.
features like these tools would be awesome to be added :
like "change pivot" and "Bake pivot"  and "to Zero {to world zero" .

https://www.unrealengine.com/marketplace/en-US/product/pivot-tool

**Comment by xyahh** [comment]
Oh nice! I did not think about the Pivots! Great idea! If I have spare time I will look into implementing part of the Pivot functionality (i.e. changing pivot offset in runtime). 

I don't think "Bake Pivot" should be a core part of this plugin though. I don't think it will work for Shipped Builds since that tool that you mention is most likely working with the static mesh assets in the editor (which are already cooked in builds). This Runtime Plugin was designed to work with Shipped versions to easily implement Map-editor tools for players. 

But, given the flexibility of this plugin, if I make the basic pivot offset functionality,  faking the "bake pivot" functionality will also be possible by storing a list of pivot offsets for a group, tag or a specific actor and apply them into the runtime transformer plugin. But this will have to be done by oneself (not included in the plugin. Although I will be more willing to assist on how to implement it...) 

Thank you so much for your feedback !
